-- AlterTable
ALTER TABLE "Submission"
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'DRAFT',
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "status" SET DEFAULT 'DRAFT',
ALTER COLUMN "score" SET DEFAULT 0,
ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total" SET DEFAULT 0,
ALTER COLUMN "total" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "percentage" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "SubmissionAnswer"
ADD COLUMN IF NOT EXISTS "earnedPoints" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "maxPoints" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Submission_examId_idx" ON "Submission"("examId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Submission_studentId_idx" ON "Submission"("studentId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "SubmissionAnswer_submissionId_idx" ON "SubmissionAnswer"("submissionId");
